### ISSUE TITLE
Watermark on popup image

### ISSUE THREAD

**Issue by Aw3same** [sanjayV/ng-image-slider#126]
Is it possible to add a watermark in the big image? I'm trying it in the same way as in the examples, by overriding css, but I cant see my watermark in front of image.

![image](https://user-images.githubusercontent.com/10500082/124468494-75bd3100-dd99-11eb-8cf6-bc18dab5399f.png)

my css is
```css
ng-image-slider .lightbox-div {
  z-index: 12;
  content: "";
  display: block;
  width: 100%;
  height: 100%;
  position: relative;
  top: 0px;
  left: 0px;
  background-image: url("/assets/images/confidential.png");
  background-size: 300px 300px;
  background-repeat: space;
  opacity: 0.9;
}
``` 

Thanks in advance
